#!/bin/sh
# A file as C: a plain byte array (od), so no compiler needs #embed. The
# program links it as NAME and NAME_len (edt_fbb, edt_fbb_len).
set -eu
name=${1:?usage: embed.sh NAME FILE}
file=${2:?usage: embed.sh NAME FILE}
printf '/* generated by embed.sh from %s: do not edit */\n' "$file"
printf '#include <stddef.h>\n#include <stdint.h>\n\n'
printf '_Alignas(8) const uint8_t %s[] = {\n' "$name"
od -An -v -tu1 "$file" | awk '{for (i = 1; i <= NF; i++) printf "%s,", $i; print ""}'
printf '};\n\nconst size_t %s_len = sizeof %s;\n' "$name" "$name"
