#!/usr/bin/env python3
"""Generates the wide-rune table: src/width_table.h, or with -go compterm's
mterm/width_table.go. Both come from this script so the two stay mirrors.

Wide = the East Asian blocks below plus every Emoji_Presentation=Yes rune from
Unicode's emoji-data.txt, which terminals (tmux, iTerm2, xterm, Ghostty)
render as two columns.

Usage:
    curl -sfLO https://www.unicode.org/Public/UCD/latest/ucd/emoji/emoji-data.txt
    python3 tools/gen_width.py emoji-data.txt > src/width_table.h
    python3 tools/gen_width.py -go emoji-data.txt > ../compterm/mterm/width_table.go
"""
import re
import sys

EAST_ASIAN = [
    (0x1100, 0x115F), (0x2329, 0x232A), (0x2E80, 0x2FFB), (0x3000, 0x303E),
    (0x3041, 0x33FF), (0x3400, 0x4DBF), (0x4E00, 0x9FFF), (0xA000, 0xA4CF),
    (0xA960, 0xA97C), (0xAC00, 0xD7A3), (0xF900, 0xFAFF), (0xFE10, 0xFE19),
    (0xFE30, 0xFE6B), (0xFF00, 0xFF60), (0xFFE0, 0xFFE6), (0x16FE0, 0x16FE4),
    (0x17000, 0x18CD5), (0x1B000, 0x1B2FB), (0x1F300, 0x1F64F), (0x1F680, 0x1F6FF),
    (0x1F900, 0x1F9FF), (0x1FA70, 0x1FAFF), (0x20000, 0x2FFFD), (0x30000, 0x3FFFD),
]

LINE = re.compile(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*Emoji_Presentation\b")


def emoji_presentation(path):
    out = []
    version = "?"
    with open(path, encoding="utf-8") as f:
        for line in f:
            if line.startswith("# emoji-data-") or line.startswith("# Version:"):
                version = line.split()[-1]
            m = LINE.match(line)
            if m:
                lo = int(m.group(1), 16)
                out.append((lo, int(m.group(2) or m.group(1), 16)))
    return out, version


def merge(ranges):
    out = []
    for lo, hi in sorted(ranges):
        if out and lo <= out[-1][1] + 1:
            out[-1] = (out[-1][0], max(out[-1][1], hi))
        else:
            out.append((lo, hi))
    return out


def emit_c(ranges, src):
    w = sys.stdout.write
    w("/* Generated by tools/gen_width.py from %s. Do not edit. */\n" % src)
    w("#ifndef FILO_TERM_WIDTH_TABLE_H\n#define FILO_TERM_WIDTH_TABLE_H\n\n")
    w("/* clang-format off */\nstatic const range wide_runes[] = {\n")
    for lo, hi in ranges:
        w("    {0x%04X, 0x%04X},\n" % (lo, hi))
    w("};\n/* clang-format on */\n\n#endif\n")


def emit_go(ranges, src):
    w = sys.stdout.write
    w("// Code generated by filo-term tools/gen_width.py from %s. DO NOT EDIT.\n\n" % src)
    w("package mterm\n\nimport \"unicode\"\n\n")
    w("var wideRunes = &unicode.RangeTable{\n")
    w("\tR16: []unicode.Range16{\n")
    for lo, hi in ranges:
        if hi <= 0xFFFF:
            w("\t\t{Lo: 0x%04X, Hi: 0x%04X, Stride: 1},\n" % (lo, hi))
    w("\t},\n\tR32: []unicode.Range32{\n")
    for lo, hi in ranges:
        if lo > 0xFFFF:
            w("\t\t{Lo: 0x%04X, Hi: 0x%04X, Stride: 1},\n" % (lo, hi))
    w("\t},\n}\n")


def main():
    args = sys.argv[1:]
    go = "-go" in args
    args = [a for a in args if a != "-go"]
    if len(args) != 1 or args[0] in ("-h", "--help"):
        sys.stdout.write(__doc__)
        sys.exit(0 if args and args[0] in ("-h", "--help") else 2)
    emoji, version = emoji_presentation(args[0])
    if not emoji:
        sys.exit("gen_width: no Emoji_Presentation entries in %s" % args[0])
    ranges = merge(EAST_ASIAN + emoji)
    if any(lo <= 0xFFFF < hi for lo, hi in ranges):
        sys.exit("gen_width: a range straddles U+FFFF")
    src = "emoji-data.txt %s" % version
    if go:
        emit_go(ranges, src)
    else:
        emit_c(ranges, src)


main()
