#include "utf8.h"

void utf8_dec_init(utf8_dec *d) {
    d->cp = 0;
    d->need = 0;
    d->have = 0;
}

utf8_result utf8_dec_feed(utf8_dec *d, uint8_t b, uint32_t *cp, int *resync) {
    *resync = 0;
    if (d->need == 0) {
        if (b < 0x80) {
            *cp = b;
            d->bytes[0] = b;
            d->have = 1;
            return UTF8_RUNE;
        }
        if (b >= 0xC2 && b <= 0xDF) {
            d->cp = (uint32_t)(b & 0x1FU);
            d->need = 1;
        } else if (b >= 0xE0 && b <= 0xEF) {
            d->cp = (uint32_t)(b & 0x0FU);
            d->need = 2;
        } else if (b >= 0xF0 && b <= 0xF4) {
            d->cp = (uint32_t)(b & 0x07U);
            d->need = 3;
        } else {
            /* 0x80..0xC1 stray continuation or overlong lead */
            d->have = 0;
            return UTF8_ERROR;
        }
        d->bytes[0] = b;
        d->have = 1;
        return UTF8_MORE;
    }
    if ((b & 0xC0U) != 0x80U) {
        /* sequence broken; this byte starts something new */
        utf8_dec_init(d);
        *resync = 1;
        return UTF8_ERROR;
    }
    d->cp = (d->cp << 6U) | (uint32_t)(b & 0x3FU);
    d->bytes[d->have] = b;
    d->have++;
    d->need--;
    if (d->need > 0) {
        return UTF8_MORE;
    }
    /* reject overlong, surrogates and out of range */
    if (d->cp > 0x10FFFF || (d->cp >= 0xD800 && d->cp <= 0xDFFF) ||
        (d->have == 2 && d->cp < 0x80) || (d->have == 3 && d->cp < 0x800) ||
        (d->have == 4 && d->cp < 0x10000)) {
        utf8_dec_init(d);
        return UTF8_ERROR;
    }
    *cp = d->cp;
    return UTF8_RUNE;
}

typedef struct {
    uint32_t lo;
    uint32_t hi;
} range;

/* East Asian Wide/Fullwidth blocks plus Emoji_Presentation runes, mirrored
   from compterm mterm/width.go (both generated by tools/gen_width.py):
   counting a wide rune as one column makes re-rendered lines overflow (the
   duplicated tmux bar bug). */
#include "width_table.h"

/* Practical zero-width subset (combining marks, joiners, variation selectors,
   BOM). mterm uses Go's unicode.Mn/Me/Cf; these are the blocks that occur in
   real text on this site. */
static const range zero_runes[] = {
    {0x0300, 0x036F}, {0x0483, 0x0489}, {0x0591, 0x05BD},   {0x0610, 0x061A}, {0x064B, 0x065F},
    {0x06D6, 0x06DC}, {0x0E31, 0x0E31}, {0x0E34, 0x0E3A},   {0x1AB0, 0x1AFF}, {0x1DC0, 0x1DFF},
    {0x200B, 0x200F}, {0x2028, 0x202E}, {0x2060, 0x2064},   {0x20D0, 0x20FF}, {0xFE00, 0xFE0F},
    {0xFE20, 0xFE2F}, {0xFEFF, 0xFEFF}, {0xE0100, 0xE01EF},
};

/* r must be sorted and non-overlapping. */
static int in_ranges(const range *r, size_t n, uint32_t cp) {
    size_t lo = 0;
    size_t hi = n;
    while (lo < hi) {
        size_t mid = lo + ((hi - lo) / 2);
        if (cp < r[mid].lo) {
            hi = mid;
        } else if (cp > r[mid].hi) {
            lo = mid + 1;
        } else {
            return 1;
        }
    }
    return 0;
}

int utf8_width(uint32_t cp) {
    if (cp < 0x20 || (cp >= 0x7F && cp < 0xA0)) {
        return 0; /* control bytes never reach the screen as glyphs */
    }
    if (cp < 0x300) {
        return 1; /* below every range: most of what a screen holds */
    }
    if (in_ranges(zero_runes, sizeof(zero_runes) / sizeof(zero_runes[0]), cp)) {
        return 0;
    }
    if (in_ranges(wide_runes, sizeof(wide_runes) / sizeof(wide_runes[0]), cp)) {
        return 2;
    }
    return 1;
}

size_t utf8_swidth(const char *s) {
    utf8_dec d;
    utf8_dec_init(&d);
    size_t w = 0;
    size_t i = 0;
    while (s[i] != '\0') {
        uint32_t cp = 0;
        int resync = 0;
        utf8_result r = utf8_dec_feed(&d, (uint8_t)s[i], &cp, &resync);
        if (r == UTF8_RUNE) {
            w += (size_t)utf8_width(cp);
        }
        if (r == UTF8_ERROR) {
            w += 1; /* rendered as replacement */
            if (resync) {
                continue; /* re-feed same byte */
            }
        }
        i++;
    }
    return w;
}

size_t utf8_last_rune_len(const uint8_t *buf, size_t len) {
    if (len == 0) {
        return 0;
    }
    size_t n = 1;
    while (n < len && n < UTF8_MAX_BYTES && (buf[len - n] & 0xC0U) == 0x80U) {
        n++;
    }
    return n;
}

size_t utf8_encode(uint8_t buf[UTF8_MAX_BYTES], uint32_t cp) {
    if (cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF)) {
        cp = UTF8_REPLACEMENT;
    }
    if (cp < 0x80) {
        buf[0] = (uint8_t)cp;
        return 1;
    }
    if (cp < 0x800) {
        buf[0] = (uint8_t)(0xC0U | (cp >> 6U));
        buf[1] = (uint8_t)(0x80U | (cp & 0x3FU));
        return 2;
    }
    if (cp < 0x10000) {
        buf[0] = (uint8_t)(0xE0U | (cp >> 12U));
        buf[1] = (uint8_t)(0x80U | ((cp >> 6U) & 0x3FU));
        buf[2] = (uint8_t)(0x80U | (cp & 0x3FU));
        return 3;
    }
    buf[0] = (uint8_t)(0xF0U | (cp >> 18U));
    buf[1] = (uint8_t)(0x80U | ((cp >> 12U) & 0x3FU));
    buf[2] = (uint8_t)(0x80U | ((cp >> 6U) & 0x3FU));
    buf[3] = (uint8_t)(0x80U | (cp & 0x3FU));
    return 4;
}
